<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>AzureFunctions.PowerShell.Durable.SDK</AssemblyName>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DurableEngine\DurableEngine.csproj" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.18" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AzureFunctions.PowerShell.Durable.SDK.E2E" />
  </ItemGroup>
</Project>
