// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shared/NullableTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from shared/NullableTypes.proto</summary>
public static partial class NullableTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for shared/NullableTypes.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static NullableTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpzaGFyZWQvTnVsbGFibGVUeXBlcy5wcm90bxofZ29vZ2xlL3Byb3RvYnVm",
          "L3RpbWVzdGFtcC5wcm90byIrCg5OdWxsYWJsZVN0cmluZxIPCgV2YWx1ZRgB",
          "IAEoCUgAQggKBnN0cmluZyIrCg5OdWxsYWJsZURvdWJsZRIPCgV2YWx1ZRgB",
          "IAEoAUgAQggKBmRvdWJsZSInCgxOdWxsYWJsZUJvb2wSDwoFdmFsdWUYASAB",
          "KAhIAEIGCgRib29sIk0KEU51bGxhYmxlVGltZXN0YW1wEisKBXZhbHVlGAEg",
          "ASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAQgsKCXRpbWVzdGFt",
          "cEIsCipjb20ubWljcm9zb2Z0LmF6dXJlLmZ1bmN0aW9ucy5ycGMubWVzc2Fn",
          "ZXNiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NullableString), global::NullableString.Parser, new[]{ "Value" }, new[]{ "String" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NullableDouble), global::NullableDouble.Parser, new[]{ "Value" }, new[]{ "Double" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NullableBool), global::NullableBool.Parser, new[]{ "Value" }, new[]{ "Bool" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NullableTimestamp), global::NullableTimestamp.Parser, new[]{ "Value" }, new[]{ "Timestamp" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class NullableString : pb::IMessage<NullableString> {
  private static readonly pb::MessageParser<NullableString> _parser = new pb::MessageParser<NullableString>(() => new NullableString());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<NullableString> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NullableTypesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableString() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableString(NullableString other) : this() {
    switch (other.StringCase) {
      case StringOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableString Clone() {
    return new NullableString(this);
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Value {
    get { return stringCase_ == StringOneofCase.Value ? (string) string_ : ""; }
    set {
      string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      stringCase_ = StringOneofCase.Value;
    }
  }

  private object string_;
  /// <summary>Enum of possible cases for the "string" oneof.</summary>
  public enum StringOneofCase {
    None = 0,
    Value = 1,
  }
  private StringOneofCase stringCase_ = StringOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StringOneofCase StringCase {
    get { return stringCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearString() {
    stringCase_ = StringOneofCase.None;
    string_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as NullableString);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(NullableString other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Value != other.Value) return false;
    if (StringCase != other.StringCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (stringCase_ == StringOneofCase.Value) hash ^= Value.GetHashCode();
    hash ^= (int) stringCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (stringCase_ == StringOneofCase.Value) {
      output.WriteRawTag(10);
      output.WriteString(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (stringCase_ == StringOneofCase.Value) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(NullableString other) {
    if (other == null) {
      return;
    }
    switch (other.StringCase) {
      case StringOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Value = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class NullableDouble : pb::IMessage<NullableDouble> {
  private static readonly pb::MessageParser<NullableDouble> _parser = new pb::MessageParser<NullableDouble>(() => new NullableDouble());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<NullableDouble> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NullableTypesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableDouble() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableDouble(NullableDouble other) : this() {
    switch (other.DoubleCase) {
      case DoubleOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableDouble Clone() {
    return new NullableDouble(this);
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double Value {
    get { return doubleCase_ == DoubleOneofCase.Value ? (double) double_ : 0D; }
    set {
      double_ = value;
      doubleCase_ = DoubleOneofCase.Value;
    }
  }

  private object double_;
  /// <summary>Enum of possible cases for the "double" oneof.</summary>
  public enum DoubleOneofCase {
    None = 0,
    Value = 1,
  }
  private DoubleOneofCase doubleCase_ = DoubleOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DoubleOneofCase DoubleCase {
    get { return doubleCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDouble() {
    doubleCase_ = DoubleOneofCase.None;
    double_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as NullableDouble);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(NullableDouble other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
    if (DoubleCase != other.DoubleCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (doubleCase_ == DoubleOneofCase.Value) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
    hash ^= (int) doubleCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (doubleCase_ == DoubleOneofCase.Value) {
      output.WriteRawTag(9);
      output.WriteDouble(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (doubleCase_ == DoubleOneofCase.Value) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(NullableDouble other) {
    if (other == null) {
      return;
    }
    switch (other.DoubleCase) {
      case DoubleOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Value = input.ReadDouble();
          break;
        }
      }
    }
  }

}

public sealed partial class NullableBool : pb::IMessage<NullableBool> {
  private static readonly pb::MessageParser<NullableBool> _parser = new pb::MessageParser<NullableBool>(() => new NullableBool());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<NullableBool> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NullableTypesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableBool() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableBool(NullableBool other) : this() {
    switch (other.BoolCase) {
      case BoolOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableBool Clone() {
    return new NullableBool(this);
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Value {
    get { return boolCase_ == BoolOneofCase.Value ? (bool) bool_ : false; }
    set {
      bool_ = value;
      boolCase_ = BoolOneofCase.Value;
    }
  }

  private object bool_;
  /// <summary>Enum of possible cases for the "bool" oneof.</summary>
  public enum BoolOneofCase {
    None = 0,
    Value = 1,
  }
  private BoolOneofCase boolCase_ = BoolOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BoolOneofCase BoolCase {
    get { return boolCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBool() {
    boolCase_ = BoolOneofCase.None;
    bool_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as NullableBool);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(NullableBool other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Value != other.Value) return false;
    if (BoolCase != other.BoolCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (boolCase_ == BoolOneofCase.Value) hash ^= Value.GetHashCode();
    hash ^= (int) boolCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (boolCase_ == BoolOneofCase.Value) {
      output.WriteRawTag(8);
      output.WriteBool(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (boolCase_ == BoolOneofCase.Value) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(NullableBool other) {
    if (other == null) {
      return;
    }
    switch (other.BoolCase) {
      case BoolOneofCase.Value:
        Value = other.Value;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Value = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class NullableTimestamp : pb::IMessage<NullableTimestamp> {
  private static readonly pb::MessageParser<NullableTimestamp> _parser = new pb::MessageParser<NullableTimestamp>(() => new NullableTimestamp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<NullableTimestamp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NullableTypesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableTimestamp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableTimestamp(NullableTimestamp other) : this() {
    switch (other.TimestampCase) {
      case TimestampOneofCase.Value:
        Value = other.Value.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NullableTimestamp Clone() {
    return new NullableTimestamp(this);
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Value {
    get { return timestampCase_ == TimestampOneofCase.Value ? (global::Google.Protobuf.WellKnownTypes.Timestamp) timestamp_ : null; }
    set {
      timestamp_ = value;
      timestampCase_ = value == null ? TimestampOneofCase.None : TimestampOneofCase.Value;
    }
  }

  private object timestamp_;
  /// <summary>Enum of possible cases for the "timestamp" oneof.</summary>
  public enum TimestampOneofCase {
    None = 0,
    Value = 1,
  }
  private TimestampOneofCase timestampCase_ = TimestampOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TimestampOneofCase TimestampCase {
    get { return timestampCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimestamp() {
    timestampCase_ = TimestampOneofCase.None;
    timestamp_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as NullableTimestamp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(NullableTimestamp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Value, other.Value)) return false;
    if (TimestampCase != other.TimestampCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (timestampCase_ == TimestampOneofCase.Value) hash ^= Value.GetHashCode();
    hash ^= (int) timestampCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (timestampCase_ == TimestampOneofCase.Value) {
      output.WriteRawTag(10);
      output.WriteMessage(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (timestampCase_ == TimestampOneofCase.Value) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(NullableTimestamp other) {
    if (other == null) {
      return;
    }
    switch (other.TimestampCase) {
      case TimestampOneofCase.Value:
        if (Value == null) {
          Value = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Value.MergeFrom(other.Value);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          if (timestampCase_ == TimestampOneofCase.Value) {
            subBuilder.MergeFrom(Value);
          }
          input.ReadMessage(subBuilder);
          Value = subBuilder;
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
