name: Run tests

on:
  push:
    branches:
      - main
      - dajustp/add-gh-action-tests
    paths-ignore: [ '**.md' ]
  pull_request:
    branches:
      - main
      - dajustp/add-gh-action-tests
    paths-ignore: [ '**.md' ]

env:
  AzureWebJobsStorage: UseDevelopmentStorage=true


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: 'Install .NET 3.1'
      run: |
          Import-Module ".\pipelineUtilities.psm1" -Force
          Install-Dotnet

    - name: 'Build'
      run: ./build.ps1 -Configuration Release
